# Vectors and Matrixes with Numpy

In this workbook we will dig a little deeper into the Numpy library to specifically highlight how you can work with _vectors_ and _matrixes_ using Numpy. Those of you that are familiar with MatLab may find that Numpy is a little more clumsy and sometimes a bit confusing. This is one of the costs of using a general programming language, compared to the dedicated linear algebra application that is MatLab. I hope that with a little attention you can get comfortable with Numpy _vectors_ and _matrixes_.

Note that Numpy is now heavily used by _data scientists_, and that an ever increasing number of packages are build on top of Numpy. In that sense, the underlying math has been increadibly well tested and is very reliable.

## Vectors

There is actually no object in Numpy (or Python) that is designated as a _vector_, and there are only a few specific widely used packages that I know of that implement a physics 3-vector (one of them is visual python, or vpython), although you can find many examples of people that wrote their own. This may be an oversight, or perhaps it reflects the idea that the general _array_ object of Numpy does what is needed, and it is difficult to actually do better. The alternative is to use one of the C++ 3- and 4-vector libraries that have a Python interface (ROOT, GEANT4, CLHEP)

### Vector = np.array

So the basic vector-like object in Python was already introduced in the [Intro to Numpy](https://github.com/mholtrop/Phys601/blob/master/Notebooks/02_Intro_Numpy.ipynb) notebook. Here we will investigate the properties of the `np.array`, and the related `np.matrix` a bit further, so we can use this knowledge later.

In most respects, the `np.array` object behaves as you would expect from a _mathematical vector_, while the Python `list` object definitely does not. A simple example shows you how different they are:

In [101]:
import numpy as np
L = [1,2,3]
V = np.array([1,2,3])    # This seems to be the same thing, but it is not.
print(L*3)               # Multiply a list gives you a list that is N times as long.
print(V*3)               # Multiply a vector gives you a vector with each element N times larger.

[1, 2, 3, 1, 2, 3, 1, 2, 3]
[3 6 9]


The `np.array` and the `list` each have their specific uses. The `list` can contain mixed data (integers, floats, strings), the `np.array` has one kind of data, but is far more useful for numeric computations.

### Caution

Althought the `np.array` has ways in which it behaves like a mathematical vector, there are some points that need specific caution. **All operations on np.arrays are <font style="color:red">element wise!</font>** This is the correct behavior for many data science operations, but not what you expect if you are thinking vectors.

Some examples should make this clear:

In [126]:
A = np.array([1,2,3])
B = np.array([3,1,2])
print(A*B)            # This multiplies each element of A with that of B. Not a vector dot product!!!
print(A**2)           # This is not the A.A, but the square of each element.

[3 2 6]
[1 4 9]


### Basic Vector Operations

To get the basic vector operations we use the appropriate Numpy function. For the **dot product**, you can either use the [`np.dot`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.dot.html) function, or in Python 3.5 and up the `@` operator. (Note that in neither case there is complex conjugation!) There is also the function [`np.inner`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.inner.html), which for a 1-D array gives the same as a dot product. For 2-D (conventional matrixes) and higher, these two behave differently: np.dot is the sum product over the last axis with the one but last axis, while np.inner is the sum product over the last axis.

$$ \vec A = \left(\begin{array}{c} 1\\2\\3 \end{array}\right)\qquad \vec B = \left(\begin{array}{c} 3\\1\\2 \end{array}\right)\qquad \vec A\cdot \vec B = 11$$

In [127]:
print(np.dot(A,B))
print(A.dot(B))
print(A@B)

11
11
11


For `np.array` objects of size 2 or 3, there is also the **cross product**

$$ \vec A \times \vec B = \left(\begin{array}{c} 1\\7\\-5 \end{array}\right) $$

In [128]:
np.cross(A,B)

array([ 1,  7, -5])

You can compute the **norm** of the vector with `np.linalg.norm`, or you can calculate it as `np.sqrt(A@A)` or `np.sqrt(np.sum(A*A))`.

$$ \left | \vec A \right | = \sqrt{14} $$

You probably noticed by now that there is no difference in the representation of a row vector or a column vector. This distinction _does_ exist, but in Numpy is seen as a $1\times N$ _matrix_ or a $N\times 1$ _matrix_.

In [129]:
A.shape=(3,1) # Turn the vector A in to an 3x1 matrix.
print(A)

[[1]
 [2]
 [3]]


## Matrixes

As we just saw, the internal representation in Numpy of a _matrix_ is actually the _same_ `np.array` object. Each np.array object has an attribute called the "shape", which indicates how the internal data (a list of numbers) is to be interpreted. As we just saw, by setting the shape to a different configuration, we can can turn the np.array into a different type of object. This can be really handy when making matrixes. This also allows you to go to tensors or higher dimensions with the same set of tools. In Numpy, your matrix does not need to be a square matrix, but you do need to be careful not to have an incorrect combination!

As an example: We can take the dot product of the row vector $\vec B$ with the now column $3\times1$ matrix $A$, but not the other way around!  If we reshape $B$ into a $1\times 3$ matrix, then it _is_ allowed, but it gives the _outer product_, as it should.  

In [130]:
print(B@A)
print(A@B)

[11]


ValueError: shapes (3,1) and (3,) not aligned: 1 (dim 1) != 3 (dim 0)

In [135]:
B.shape=(1,3)
print("Now B is the matrix =",B)           # This is now a matrix. You can see the double square bracket [[]]
print("This is the outer product A@B:\n",A@B)         # So then this is the outer product of the matrixes.

Now B is the matrix = [[3 1 2]]
This is the outer product A@B:
 [[3 1 2]
 [6 2 4]
 [9 3 6]]


### Matrix multiplication

We often need to multiply a matrix with a scalar (number), a vector, or another matrix. With Numpy, we just have to be careful that the shape of the objects we multiply is correct.

Scalar multiplication is nothing special, every number in the matrix is multiplied by the scalar:

In [153]:
M1 = np.array([[1,2,3],[2,3,1],[3,1,2]])
print(M1)

[[1 2 3]
 [2 3 1]
 [3 1 2]] [[3 6 9]
 [6 9 3]
 [9 3 6]]


In [154]:
print(3*M1)

[[3 6 9]
 [6 9 3]
 [9 3 6]]


When multiplying a matrix with a vector, we need to be more careful. The `np.dot()` function usually works the way you expect. You can also use the `np.matmul()` for matrix multiplication. If you are in doubt how to use any of these functions, it is always good to do some test cases where you know the answer, and make sure that is indeed what you get.

In [173]:
v1 = np.array([0,1,0])
print(M1)
print(M1.dot(v1))
print(M1@v1)
print(np.matmul(M1,v1))

[[1 2 3]
 [2 3 1]
 [3 1 2]]
[2 3 1]
[2 3 1]
[2 3 1]


For matrix-matrix multiplication, we now have to worry about the different versions. For our $3\times 3$ matrix, it does not make a difference. We get the same result each time, however with larger dimensions there are differences.

In [176]:
M2 = np.array([[1,0,1],[0,1,0],[1,0,1]])
print(M1.dot(M2))
print(M1@M2)
print(np.matmul(M1,M2))
print(np.inner(M1,M2))

[[4 2 4]
 [3 3 3]
 [5 1 5]]
[[4 2 4]
 [3 3 3]
 [5 1 5]]
[[4 2 4]
 [3 3 3]
 [5 1 5]]
[[4 2 4]
 [3 3 3]
 [5 1 5]]
