# Vectors and Matrixes with Numpy

In this workbook we will dig a little deeper into the Numpy library to specifically highlight how you can work with _vectors_ and _matrixes_ using Numpy. Those of you that are familiar with MatLab may find that Numpy is a little more clumsy and sometimes a bit confusing. This is one of the costs of using a general programming language, compared to the dedicated linear algebra application that is MatLab. I hope that with a little attention you can get comfortable with Numpy _vectors_ and _matrixes_.

Note that Numpy is now heavily used by _data scientists_, and that an ever increasing number of packages are build on top of Numpy. In that sense, the underlying math has been increadibly well tested and is very reliable.

## Vectors

There is actually no object in Numpy (or Python) that is designated as a _vector_, and there are only a few specific widely used packages that I know of that implement a physics 3-vector (one of them is visual python, or vpython), although you can find many examples of people that wrote their own. This may be an oversight, or perhaps it reflects the idea that the general _array_ object of Numpy does what is needed, and it is difficult to actually do better. The alternative is to use one of the C++ 3- and 4-vector libraries that have a Python interface (ROOT, GEANT4, CLHEP)

### Vector = np.array

So the basic vector-like object in Python was already introduced in the [Intro to Numpy](https://github.com/mholtrop/Phys601/blob/master/Notebooks/02_Intro_Numpy.ipynb) notebook. Here we will investigate the properties of the `np.array`, and the related `np.matrix` a bit further, so we can use this knowledge later.

In most respects, the `np.array` object behaves as you would expect from a _mathematical vector_, while the Python `list` object definitely does not. A simple example shows you how different they are:

In [1]:
import numpy as np
L = [1,2,3]
V = np.array([1,2,3])    # This seems to be the same thing, but it is not.
print(L*3)               # Multiply a list gives you a list that is N times as long.
print(V*3)               # Multiply a vector gives you a vector with each element N times larger.

[1, 2, 3, 1, 2, 3, 1, 2, 3]
[3 6 9]


The `np.array` and the `list` each have their specific uses. The `list` can contain mixed data (integers, floats, strings), the `np.array` has one kind of data, but is far more useful for numeric computations.

### Caution

Althought the `np.array` has ways in which it behaves like a mathematical vector, there are some points that need specific caution. **All operations on np.arrays are <font style="color:red">element wise!</font>** This is the correct behavior for many data science operations, but not what you expect if you are thinking vectors.

Some examples should make this clear:

In [2]:
A = np.array([1,2,3])
B = np.array([3,1,2])
print(A*B)            # This multiplies each element of A with that of B. Not a vector dot product!!!
print(A**2)           # This is not the A.A, but the square of each element.

[3 2 6]
[1 4 9]


### Basic Vector Operations

To get the basic vector operations we use the appropriate Numpy function. For the **dot product**, you can either use the [`np.dot`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.dot.html) function, or in Python 3.5 and up the `@` operator. (Note that in neither case there is complex conjugation!) There is also the function [`np.inner`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.inner.html), which for a 1-D array gives the same as a dot product. For 2-D (conventional matrixes) and higher, these two behave differently: np.dot is the sum product over the last axis with the one but last axis, while np.inner is the sum product over the last axis.

$$ \vec A = \left(\begin{array}{c} 1\\2\\3 \end{array}\right)\qquad \vec B = \left(\begin{array}{c} 3\\1\\2 \end{array}\right)\qquad \vec A\cdot \vec B = 11$$

In [3]:
print(np.dot(A,B))
print(A.dot(B))
print(A@B)

11
11
11


For `np.array` objects of size 2 or 3, there is also the **cross product**

$$ \vec A \times \vec B = \left(\begin{array}{c} 1\\7\\-5 \end{array}\right) $$

In [4]:
np.cross(A,B)

array([ 1,  7, -5])

You can compute the **norm** of the vector with `np.linalg.norm`, or you can calculate it as `np.sqrt(A@A)` or `np.sqrt(np.sum(A*A))`.

$$ \left | \vec A \right | = \sqrt{14} $$

You probably noticed by now that there is no difference in the representation of a row vector or a column vector. This distinction _does_ exist, but in Numpy is seen as a $1\times N$ _matrix_ or a $N\times 1$ _matrix_.

In [5]:
A.shape=(3,1) # Turn the vector A in to an 3x1 matrix.
print(A)

[[1]
 [2]
 [3]]


## Matrixes

As we just saw, the internal representation in Numpy of a _matrix_ is actually the _same_ `np.array` object. Each np.array object has an attribute called the "shape", which indicates how the internal data (a list of numbers) is to be interpreted. As we just saw, by setting the shape to a different configuration, we can can turn the np.array into a different type of object. This can be really handy when making matrixes. This also allows you to go to tensors or higher dimensions with the same set of tools. In Numpy, your matrix does not need to be a square matrix, but you do need to be careful not to have an incorrect combination!

As an example: We can take the dot product of the row vector $\vec B$ with the now column $3\times1$ matrix $A$, but not the other way around!  If we reshape $B$ into a $1\times 3$ matrix, then it _is_ allowed, but it gives the _outer product_, as it should.  

In [6]:
print(B@A)
print(A@B)

[11]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 1)

In [7]:
B.shape=(1,3)
print("Now B is the matrix =",B)           # This is now a matrix. You can see the double square bracket [[]]
print("This is the outer product A@B:\n",A@B)         # So then this is the outer product of the matrixes.

Now B is the matrix = [[3 1 2]]
This is the outer product A@B:
 [[3 1 2]
 [6 2 4]
 [9 3 6]]


### Matrix multiplication

We often need to multiply a matrix with a scalar (number), a vector, or another matrix. With Numpy, we just have to be careful that the shape of the objects we multiply is correct.

Scalar multiplication is nothing special, every number in the matrix is multiplied by the scalar:

In [8]:
M1 = np.array([[1,2,3],[2,3,1],[3,1,2]])
print(M1)

[[1 2 3]
 [2 3 1]
 [3 1 2]]


In [9]:
print(3*M1)

[[3 6 9]
 [6 9 3]
 [9 3 6]]


When multiplying a matrix with a vector, we need to be more careful. The `np.dot()` function usually works the way you expect. You can also use the `np.matmul()` for matrix multiplication. If you are in doubt how to use any of these functions, it is always good to do some test cases where you know the answer, and make sure that is indeed what you get.

In [10]:
v1 = np.array([0,1,0])
print(M1)
print(M1.dot(v1))
print(M1@v1)
print(np.matmul(M1,v1))

[[1 2 3]
 [2 3 1]
 [3 1 2]]
[2 3 1]
[2 3 1]
[2 3 1]


For matrix-matrix multiplication 'dot', 'matmul' and '@' all multiply the two matrixes. There is also 'inner', which performs an inner product for vectors, or matrix-vector, but for matrix-matrix is "a sum product over the last axes", which does not seem useful.

In [11]:
M2 = np.array([[1,0,1],[0,1,0],[1,2,3]])
print(M1)
print(M2)
print(M1.dot(M2))
print(M1@M2)
print(np.matmul(M1,M2))
print(np.inner(M1,M2))

[[1 2 3]
 [2 3 1]
 [3 1 2]]
[[1 0 1]
 [0 1 0]
 [1 2 3]]
[[ 4  8 10]
 [ 3  5  5]
 [ 5  5  9]]
[[ 4  8 10]
 [ 3  5  5]
 [ 5  5  9]]
[[ 4  8 10]
 [ 3  5  5]
 [ 5  5  9]]
[[ 4  2 14]
 [ 3  3 11]
 [ 5  1 11]]


In [12]:
M3 = np.random.randint(0,16,4).reshape(2,2) 
M4 = np.random.randint(0,16,4).reshape(2,2)
print("Is 'dot' the same as 'matmul'? ",np.all(M3.dot(M4)== np.matmul(M3,M4)))
print("Is 'dot' the same as 'inner' ? ",np.all(M3.dot(M4)== np.inner (M3,M4)))

Is 'dot' the same as 'matmul'?  True
Is 'dot' the same as 'inner' ?  False


## What is the use of np.matrix ?

There is *also* a matrix class in Numpy. You can either call that with np.matrix() or the abbreviated np.mat(). What is the point of this, since all the matrix algebra can be done with np.array?

The np.array is actually *more* flexible, since it can do any dimensionality matrix, while np.matrix is only for two dimensional ones (i.e. row,column NxM). The only difference between the two is how a few of the operations work. With the np.matrix class the '\*' operator is over-written to be the same operation as 'dot', and the '\*\*' operation is correct matrix to the Nth power, instead of matrix *elements* to the Nth power. There are times that this is useful. 

You can convert from one to the other with the `.asmatrix()`


In [13]:
print("As np.array:")
M5=np.array(np.random.randint(0,16,4).reshape(2,2))
M6=np.array(np.random.randint(0,16,4).reshape(2,2))
print("Is 'dot' the same as '*'? ",np.all(M5.dot(M6)== M5*M6))
print("Is 'M5.dot(M5)' the same as 'M5**2'? ",np.all(M5.dot(M5)== M5**2))

print("\nAs np.matrix:")
M5=np.matrix(np.random.randint(0,16,4).reshape(2,2))
M6=np.matrix(np.random.randint(0,16,4).reshape(2,2))
print("Is 'dot' the same as '*'? ",np.all(M5.dot(M6)== M5*M6))
print("Is 'M5.dot(M5)' the same as 'M5**2'? ",np.all(M5.dot(M5)== M5**2))

print("\nAs np.array.asmatrix:")
M5=np.array(np.random.randint(0,16,4).reshape(2,2))
M6=np.array(np.random.randint(0,16,4).reshape(2,2))
print("Is 'dot' the same as '*'? ",np.all(M5.dot(M6)== np.asmatrix(M5)*np.asmatrix(M6)))
print("Is 'M5.dot(M5)' the same as 'M5**2'? ",np.all(M5.dot(M5)== np.asmatrix(M5)**2))



As np.array:
Is 'dot' the same as '*'?  False
Is 'M5.dot(M5)' the same as 'M5**2'?  False

As np.matrix:
Is 'dot' the same as '*'?  True
Is 'M5.dot(M5)' the same as 'M5**2'?  True

As np.array.asmatrix:
Is 'dot' the same as '*'?  True
Is 'M5.dot(M5)' the same as 'M5**2'?  True


# Matrix operations

As you would expect, all the useful matrix operations are available: `conjugate()`, `transpose()`. 
For the `np.matrix` object, some operations are available as a property: 'T' for transpose, 'I' for inverse, 'H' for Hermitian. For the `np.array` you can accomplish these with `np.transpose(M)`, `np.linalg.inv(M)` for inverse, and `M.transpose().conjugate()` for Hermitian.


In [14]:
M1=np.matrix(np.random.randint(0,16,9).reshape(3,3))
print(M1)
print(M1.T)
print(M1.I)
print(M1.H)

[[ 7 14  4]
 [ 1  3  4]
 [ 8 14  0]]
[[ 7  1  8]
 [14  3 14]
 [ 4  4  0]]
[[-3.5     3.5     2.75  ]
 [ 2.     -2.     -1.5   ]
 [-0.625   0.875   0.4375]]
[[ 7  1  8]
 [14  3 14]
 [ 4  4  0]]


Some other operations on matrixes are in the linear algebra package: [`np.linalg`](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html). Useful methods in this package are `det()` for the determinant, and `norm()` for the norm, as well as matrix equation solvers and eigen vector solvers (see below).


In [28]:
print("Determinant = ",np.linalg.det(M1))
print("Norm of the matrix = ",np.linalg.norm(M1))

Determinant =  16.000000000000007
Norm of the matrix =  23.388031127053


# Eigen values and Eigen vectors

Finding the eigenvalues and eigenvectors of a matrix is very useful in many physics problems. There are several ways to get these with Numpy. The most general is `np.linalg.eig()` which returns the eigen values and eigen vectors of a square matrix. An alternate is `np.linalg.eigh()` which does the same for a Hermitian matrix. The difference between the two is that the `eigh()` is faster, but only gives the correct answer is the matrix is Hermitian.

In [22]:
M = np.matrix([[1,0,0],[0,2,0],[0,0,3]])
M = np.matrix([[1,0,2],[0,2,0],[2,0,1]])
%time vals,vects= np.linalg.eig(M)

CPU times: user 129 µs, sys: 11 µs, total: 140 µs
Wall time: 134 µs


In [23]:
%time vals,vects= np.linalg.eigh(M)

CPU times: user 85 µs, sys: 10 µs, total: 95 µs
Wall time: 89.6 µs


Either of these functions returns the eigen values in a list and the eigen vectors as the columns of a matrix. The vectors are thus stored slightly differently than you would expect. In situations where it is more convenient to have the eigenvectors stored as rows, you can simply take the transpose of the matrix.

So in the statement above, the eigenvalues will be in `vals` and the eigenvectors in the columns of `vects`. To get the i-th individual eigenvector, you thus need to do: `vects[:,i]` to select it. (Or you can do `vects.T[i]` 

In [24]:
print("Eigen values:",vals)
print("Eigen vectors are columns of the matrix:\n",vects)

Eigen values: [-1.  2.  3.]
Eigen vectors are columns of the matrix:
 [[-0.70710678  0.         -0.70710678]
 [ 0.         -1.          0.        ]
 [ 0.70710678  0.         -0.70710678]]


In [25]:
print("Check that the eigenvectors are correct and are normalized:")
for i in range(M.shape[0]):
    # np.allclose checks if all values are numerically close. 
    # Since floating point values are often not (quite) equal.
    print(i,np.allclose(vects[:,i]*vals[i],M.dot(vects[:,i])),np.linalg.norm(vects[:,i])) 

Check that the eigenvectors are correct and are normalized:
0 True 0.9999999999999999
1 True 1.0
2 True 0.9999999999999999


A more general solver is `np.linalg.solve`, which will numerically solve matrix equations like $\mathbf A \vec x = \vec b$ for the vector $\vec x$. 

Consider the equations $2 x_0 + 3 x_1 = 3$ and $ x_0 + x_1 = 2$ and solve for $\vec x$.

In [30]:
A = np.array([[2,3],[1,1]])
B = np.array([3,2])
np.linalg.solve(A,B)

array([ 3., -1.])