# Python Loops and List Comprehension

There are two direct ways to write a loop in Python, "for" loops and "while" loops, and you should be familiar already with both of them. There is also an indirect way to write a loop, which is what *list comprehension* is.

A quick refresher of the "for" loop. The basic syntax is:
```
for item in iterable:
    loop-body
```

Here `item` is typically a variable, and `iterable` is either a Python `list`(i.e. `[0,1,2]`), a `tuple` (i.e. `(1,2,4)`), `dict` (dicionary, i.e. `{1:"one",2:"two",3:"three"}`) or a function that is a *generator* (i.e. `range(10)`). The `for` loop will set the variable equal to each item in the list in sequence, and then execute the loop body, until the list is exhausted.

The other type of loop is the `while` loop, which is even simpler:

```
while truth-value:
    loop-body
```
where `truth-value` is a boolean (either `True` or `False`) and the loop keeps executing as long as the truth-value is `True`.

You can *nest* loops in order to run over multiple lists. The inner most loop will be executed for each iteration of the loop surrounding it, so a double loop with $N$ and $M$ items in the for loops will execute the loop body $N\times M$ times. 

#### Exercise:

* Write a double loop that prints out the multiplication tables for 1 through 10.

## List Comprehension

List comprehension is a laguage feature of Python that lets you write a for loop inside the list brackets. 
When you look at the notebook [12_Faster_Programs](), we find that *list comprehension* only speeds the code up slightly. The real reason for list comprehension is that it can often lead to more elegant and readable code. 

Here is the main syntax for a list comprehension statement (see: (Python for Beginners)[https://www.pythonforbeginners.com/basics/list-comprehensions-in-python] for more):

```
[ expression for item in list if conditional ]
```

which is equivalent to the multi line code:

```
for item in list:
   if conditional:
      expression
```

The whole idea of the list comprehension is that is is *handy* to use. Part of that ease of use is that the result can be immediately the argument to some function, without needing to store the intermediate result.

Here is a simple example. We split a sentence up into a list of words, and then we want to print those words that are longer than 4 characters. Here is the code if you wrote a direct loop:

In [19]:
word_list="When you look at the notebook we find that list comprehension only speeds the code up slightly The real reason for list comprehension is that it can often lead to more elegant and readable code".split()
#
long_words=[]
for w in word_list:
    if len(w)>4:
        long_words.append(w)
print(long_words)

['notebook', 'comprehension', 'speeds', 'slightly', 'reason', 'comprehension', 'often', 'elegant', 'readable']


Here is the same code, but now written as a list comprehension:

In [2]:
print([ w for w in word_list if len(w)>4 ])

['comprehension', 'speeds', 'slightly', 'reason', 'comprehension', 'often', 'elegant', 'readable']


You can see that the code takes less space, and once you understand how list comprehension works, it is easy to understand. 

This was an example of a *filter*, a bit of code that selects specific items from a list. 

### Multi loop list comprehension

You can also make multiple loops into a single list comprehension. Here is an example, a simple bit of code that creates a matrix with numbers of 0 to 9 with the 1's on the diagonal. The standard loop would looks like this:

In [17]:
import numpy as np
result=[]
for i in range(9,0,-1):
    row=[]
    for j in range(i,9+i):
        row.append(j%9+1)
    result.append(row)
print(np.matrix(result))

[[1 2 3 4 5 6 7 8 9]
 [9 1 2 3 4 5 6 7 8]
 [8 9 1 2 3 4 5 6 7]
 [7 8 9 1 2 3 4 5 6]
 [6 7 8 9 1 2 3 4 5]
 [5 6 7 8 9 1 2 3 4]
 [4 5 6 7 8 9 1 2 3]
 [3 4 5 6 7 8 9 1 2]
 [2 3 4 5 6 7 8 9 1]]


The loop comprehension version fits everything on a single line:

In [18]:
print(np.matrix([ [j%9+1 for j in range(i,9+i)] for i in range(9,0,-1) ]))

[[1 2 3 4 5 6 7 8 9]
 [9 1 2 3 4 5 6 7 8]
 [8 9 1 2 3 4 5 6 7]
 [7 8 9 1 2 3 4 5 6]
 [6 7 8 9 1 2 3 4 5]
 [5 6 7 8 9 1 2 3 4]
 [4 5 6 7 8 9 1 2 3]
 [3 4 5 6 7 8 9 1 2]
 [2 3 4 5 6 7 8 9 1]]


#### Exercises
* Write a list comprehension filter that filters out all the numbers of a list that are divisible by both 3 and 7. Test the filter on `range(100)`.
* Write a list comprehension that transposes the 3x3 matrix: [[1,2,3],[4,5,6],[7,8,9]]. (Note: yes, this can be done with Numpy, but here that would be cheating.)

## Generators

Generators are special functions in Python that return a new value each time they are invoked *inside a for loop*, or by using the special keyword `next()`. Although the `range()` function is not quite a generator (it is an *immutable iterator*) it has properties similar to a generator in that it gives a new value each time the `for` loop asks for one.

Generators make use of a special keyword in Python, `yield()`. When Python encounters the `yield()` statement in a function, it will stop right there and return the value of the `yield()`. This is similar to the `return()` statement, however, with the `yield()` statement, the *next* time you call the same function, it *continues at the next statement after the `yield()`*. All the variables in your function will still contain the value they had when the `yield()` was invoked. This is different from a normal function with a `return()` statement, since the next time you call that function it will start again from the beginning and all the variables are reset. 

An example hopefully makes this more clear. The following function works like `range(N)`, returning successive values starting at 0, and going upto N.

In [29]:
def my_range(N):
    count = 0
    while count<N:
        yield(count)
        count += 1


In [30]:
list(my_range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [31]:
xr=my_range(5)
print(next(xr))
print(next(xr))

0
1


In many cases there is no real need for a generator. You can simply make a list and then iterate over that list in your `for` loop. However, when you get very long lists, that can consume a lot of memory and therefore be inefficient. In those cases it would be better to write a generator. Another situation in which a generator can be useful is when you do not know ahead of time when the loop should stop. A list would then have to be very long, just in case, while the generator can just keep going until something else causes the end of the loop. An example of such an endless generator would be the random number generator.

A more detailed explanation, including on how to communicate with the generator after it has started, can be found in this article [Improve your python yield, and generators explained.](https://jeffknupp.com/blog/2013/04/07/improve-your-python-yield-and-generators-explained/)

A bit silly example of a generator that continuously returns the sequence: 1,5,3,2,4 could be written as:

In [32]:
def silly1():
    while True:
        yield(1)
        yield(5)
        yield(3)
        yield(2)
        yield(4)

Be careful using this! The statement `list(silly1())` will never return.

#### Exersizes:

* Improve the `silly1()` generator so that it stops after it has produces N sequences.
* Furthen improve the `silly1()` generator so that it will do an arbitrary sequence N times, where the sequence is supplied as an argument.

#### More Exersizes:
* Write a generator that returns the successive numnbers of the [Fibonnaci Sequence](https://en.wikipedia.org/wiki/Fibonacci_number), for up to N numbers.
* Write a list comprehension that successively calls the Fibonnaci_generator for the first 100 numbers of the sequence, and then filters out those that are perfect squares. Hint: You can test for a perfect square with `math.sqrt(x).is_integer()` for values of x up to 4503599627370496 

*Note:* You can use the `mpmath.fibonacci()` function to test your sequence. Note that this is not a generator, and using it would be cheating. If you want to test for a perfect square for larger numbers, you would need to use mpmath with a large `mpmath.mp.dps` setting, and call `mpmath.isint(mpmath.sqrt(x))`.