# Intro to Numpy

While the basic Python language is already quite useful for basic calculation, you need a bit more to do Linear Algebra with ease. The module "Numpy" (short for Numerical Python), is intended to fill this gap. Documentation: [http://www.numpy.org](http://www.numpy.org)

You can find lots of details on how to use Numpy and what you can do with it in the documentation, and in one of our books: See chapter 3 of *Scientific Computing with Python*.

Here I will focus mostly on some very basic usage, so that you can get started with Numpy.

First, you need to import the Numpy package (module). In many books, you will see this done with "from numpy import *". I advice against this. The deeper reason for that advice is that there are implementations of functions like sin() and cos() in both Math and Numpy. If you import Numpy with "from numpy import *" and you import Math with "from math import *", then you cannot be sure which version of cos() is used when (actually, it will use the last one imported, so the Math one in this case). Instead we do:

In [1]:
import numpy as np   # This imports numpy, but names it "np" you need to type less.

You can now access all of Numpy's functionality, but precede the functions with "np."

## Numpy arrays

When doing Linear Algebra, you are usuallt working with N-dimensional vectors and NxN dimensional matrixes, and sometimes NxNxN dimensional tensors or higher order systems.
These Numpy arrays differ from Python "lists" (i.e. \["a",1, 3.141 \]) in that each element of the Numpy array must be of the same numerical type, usually a float, but it can also be an integer or boolean, or even a character. If you try to mix them, Numpy will use a type that can encompass all the data.

There are different ways to make an N dimensional array in Numpy. Here are some useful examples.

In [2]:
a1 = np.array([1,2,3,4])                     # An array of integers.
a2 = np.array([5.,6,7,8])                    # An array of floats
a3 = np.array([10,11,12,13],dtype="float64") # Specifically tell Numpy the data type you want.
a4 = np.array([1.+1.j,1.j,1.,-1j])           # An array of complex numbers.
a5 = np.array([1,0]*2)                       # [1,0,1,0]
zeros = np.zeros(4)                          # Fill an array of lenght 4 with zeroes
ones  = np.ones(4)                           # same, but ones this time.
onesC = np.ones(4,dtype="complex")
random= np.random.rand(4)                    # Fill with 4 random numbers between 0 and 1.
x1 = np.arange(0.,1.,0.1)       # Fill from 0. to one step before 1. with step of 0.1
x2 = np.linspace(0.,1.,11)      # Fill from 0. to 1. in 11 steps, including both end points.
print(a4,onesC,random)
print(x1)
print(x2)

[ 1.+1.j  0.+1.j  1.+0.j -0.-1.j] [1.+0.j 1.+0.j 1.+0.j 1.+0.j] [0.60651636 0.51611825 0.28474313 0.23462916]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


### Array Operations
You can do all the expected operations with a vector. Multiply by scaler, add them, etc. Note that these operatons are *different* from doing the same thing with a list!!!

In [3]:
a1*5          # Proper vector multiplication with scalar.

array([ 5, 10, 15, 20])

In [4]:
[1,2,3,4]*5   # List multiplication gives you N times the list. Not what you want in algebra!

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [5]:
a1*2 + a2*0.3

array([ 3.5,  5.8,  8.1, 10.4])

Be careful however with the * operator. It **does not work as expected between vectors** (this is one the MatLab arguments against Python, BTW)

You get the dot product in one of two ways:

In [6]:
print(a1.dot(a2))   # This always worked with Python and Numpy.
print(a1 @ a2 )     # This is a new syntax, introduced in Python 3.5

70.0
70.0


In [7]:
print( a1*a2)      # This returns the "element wise" multiplication [a1[0]*a2[0],a1[1]*a2[1],...]

[ 5. 12. 21. 32.]


There is a good reason for this behavior of Numpy, it allows for very fast vector-wise operations. If you have large data sets in a Numpy arrays, you can create a formula with the arrays themselves, and Numpy will calculate the result **for each element**. So instead of having to program: 

In [8]:
out1 = np.zeros(4) 
for i in range(len(a1)):
    out1[i] = a1[i]*a2[i]
print(out1)

[ 5. 12. 21. 32.]


You can do the much faster, and easier to program:

In [9]:
out2 = a1*a2
print(out2, out2==out1)

[ 5. 12. 21. 32.] [ True  True  True  True]


For large arrays, and complex operations on them, this isn't only easier to write, it is a huge amount faster.

## Matrixes
To do linear algebra, we need matrixes. Note that the matrixes do not need to be square. Here we need **to pay attention with Numpy**. There are 2 different ways of making a NxM matrix. One way is to make a NxN array. This will behave exactly as the N array, except that Numpy keeps track of the extra dimension of the matrix:

In [10]:
a1 = np.array([1,2,3])
V1 = np.array([[1,2,3]])
M1 = np.array([[0,1,3],[1,2,3],[4,5,6]])
print("Array a1: \n",a1,"\nHas shape: ", a1.shape," number of dimensions = ",a1.ndim)
print("Array V1: \n",V1,"\nHas shape: ", V1.shape," number of dimensions = ",V1.ndim)
print("Array M1: \n",M1,"\nHas shape: ", M1.shape," number of dimensions = ",M1.ndim)

Array a1: 
 [1 2 3] 
Has shape:  (3,)  number of dimensions =  1
Array V1: 
 [[1 2 3]] 
Has shape:  (1, 3)  number of dimensions =  2
Array M1: 
 [[0 1 3]
 [1 2 3]
 [4 5 6]] 
Has shape:  (3, 3)  number of dimensions =  2


The other way is by making this a "matrix" object rather than an array object. The matrix object behaves subtly different for operations from the array:

In [11]:
V2 = np.matrix([[1,2,3]])
M2 = np.matrix([[0,1,3],[1,2,3],[4,5,6]])
print("Matrix V2: \n",V2,"\nHas shape: ", V2.shape)
print("Matrix M2: \n",M2,"\nHas shape: ", M2.shape)

Matrix V2: 
 [[1 2 3]] 
Has shape:  (1, 3)
Matrix M2: 
 [[0 1 3]
 [1 2 3]
 [4 5 6]] 
Has shape:  (3, 3)


In [12]:
M1*V1  # This is an item, by item 

array([[ 0,  2,  9],
       [ 1,  4,  9],
       [ 4, 10, 18]])

In [13]:
M2*V2  # This gives an error. The shapes don't work because you need the column vector.

ValueError: shapes (3,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

So note here the importance of "shape". Think about what Numpy does, it always treats things like matrixes. You can multiply an NxM matrix with an MxN matrix, but not an NxM matrix with another NxM matrix if N!=M. 
The way out is to transpose the row vector to a column vector.

In [14]:
print("Shape of V1   = ",V1.shape," number of dimensions = ",V1.ndim)
print("Shape of V1.T = ",V1.T.shape," number of dimensions = ",V1.T.ndim)

Shape of V1   =  (1, 3)  number of dimensions =  2
Shape of V1.T =  (3, 1)  number of dimensions =  2


In [15]:
print("M1*V1.T = \n",M1*V1.T)  # This is not matrix * vector multiplication, it is item by item multiplication.
print("M2*V2.T = \n",M2*V2.T)  # This works as expeced, you get a new column vector.

M1*V1.T = 
 [[ 0  1  3]
 [ 2  4  6]
 [12 15 18]]
M2*V2.T = 
 [[11]
 [14]
 [32]]


In [16]:
print(M1.dot(V1.T))    # The dot product works as expected either way.
print(M2.dot(V2.T))
print(np.all(M1.dot(V1.T)== M2.dot(V2.T))) # The np.all checks if all are True.

[[11]
 [14]
 [32]]
[[11]
 [14]
 [32]]
True


In [17]:
print(M1@V1.T)    # The dot product works as expected either way.
print(M2@V2.T)
print(np.all(M1@V1.T== M2@V2.T)) # The np.all checks if all are True.

[[11]
 [14]
 [32]]
[[11]
 [14]
 [32]]
True


So why have the matrix class at all then, if it is only confusing?
Well, it has two very useful functions. Besides the transpose (M.T), you can also get the Hermetian conjugate (M.H) and the inverse (M.I). The arrays do not have the Hermetian conjugate or inverse.

In [18]:
print("Hermitian conjugate of M2=\n",M2.H)
print("The inverse of M2=\n",M2.I)
print("Is M2.I*M2 the identity matrix? ",np.allclose(M2.I*M2,np.identity(3))) 
# We use the allcose() to check if all elements of one matrix are numerically close to
# the elements in the second one. Using == would require them to be identical, which will
# rarely be the case for floating point calculations.

Hermitian conjugate of M2=
 [[0 1 4]
 [1 2 5]
 [3 3 6]]
The inverse of M2=
 [[ 1.         -3.          1.        ]
 [-2.          4.         -1.        ]
 [ 1.         -1.33333333  0.33333333]]
Is M2.I*M2 the identity matrix?  True


### Moving up in dimensionality
We can go to higher dimensions, but you are not likely to need these.

In [19]:
T1 = np.zeros([3,3,3])

In [20]:
T1.ndim

3

In [21]:
X1 = np.ones([3,3,3,3,3,3])

In [22]:
X1.ndim

6

## Inner, Outer and Cross products

In [23]:
L1=np.matrix(np.linspace(1.,3.,3)) # = [1,2,3]

In [24]:
M3=np.array([[1., 3., 2.],
       [3., 0., 2.],
       [5., 3., 4.]])

In [25]:
np.all( np.inner(M3,L1) == M3@L1.T )     # Inner product of matrix and vector

True

In [26]:
np.all(np.inner(L1,M3) == L1.dot(M3.T))

True

In [27]:
np.cross([1,0,0],[0,1,0])   # Cross product of 2 3-vectors.

array([0, 0, 1])

In [28]:
np.outer(M3,M3)

array([[ 1.,  3.,  2.,  3.,  0.,  2.,  5.,  3.,  4.],
       [ 3.,  9.,  6.,  9.,  0.,  6., 15.,  9., 12.],
       [ 2.,  6.,  4.,  6.,  0.,  4., 10.,  6.,  8.],
       [ 3.,  9.,  6.,  9.,  0.,  6., 15.,  9., 12.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 2.,  6.,  4.,  6.,  0.,  4., 10.,  6.,  8.],
       [ 5., 15., 10., 15.,  0., 10., 25., 15., 20.],
       [ 3.,  9.,  6.,  9.,  0.,  6., 15.,  9., 12.],
       [ 4., 12.,  8., 12.,  0.,  8., 20., 12., 16.]])

## Some other useful operations

In [29]:
np.all(np.linalg.norm(L1) == np.sqrt( L1 @ L1.T) ) # Compute the vector norm.

True

In [30]:
L1.size                      # Get the size of the vector = number of elements.

3

In [31]:
M3.size

9

In [32]:
L1.shape

(1, 3)

In [33]:
np.linalg.det(M3)          # Determinant of the matrix, note the rouding error!

5.999999999999995

In [34]:
np.linalg.det(M3.astype('float32')) # Lower precision gives a rounded result.
# but .astype('int') would first convert to int, then inside linalg.det back to float64.

6.0

# Subsets of the array or vector: slicing

In Numpy (and in Python lists) you cat get a subset of the array using a process that is called "slicing". It takes a slice of the data.

Accessing a single element can be done the same way as you would in C or Java:

In [35]:
a1 = np.linspace(-10,10,21)
print(a1[0],a1[3]) # Note that the first element is at 0. In MatLab and Fortran it is at 1.
print(a1[-1],a1[-2])      # The last element is at -1, the one but last at -2 etc.
print(a1[21])             # This gives an error. The 21 element does not exist!

-10.0 -7.0
10.0 9.0


IndexError: index 21 is out of bounds for axis 0 with size 21

If instead of a single element you want a subset, you can specify this with the [:] notation.

In [36]:
print(a1[0:5])  # The fist 5 elements, a1[0] through a1[4]

[-10.  -9.  -8.  -7.  -6.]


In [37]:
print(a1[-5:]) # The last 5 elements. The blank mean all up to the end.
print(a1[:-5]) # All but the last 5 elements

[ 6.  7.  8.  9. 10.]
[-10.  -9.  -8.  -7.  -6.  -5.  -4.  -3.  -2.  -1.   0.   1.   2.   3.
   4.   5.]


In [38]:
print(a1[4:6],a1[-6:-4]) #  two specific sets of 2 values

[-6. -5.] [5. 6.]


In [39]:
print(a1[0:10:2]) # Every second one, starting at 0 going up to 10

[-10.  -8.  -6.  -4.  -2.]


In [40]:
print(a1[::3])   # Every third one from the entire array.

[-10.  -7.  -4.  -1.   2.   5.   8.]


In [41]:
BigM = np.array(range(100)).reshape(10,10)  # A 10x10 array with the numbers 0 to 99

In [42]:
print(BigM[5][8],BigM[5,8]) # Two different ways of getting the x=8,y=5 element of BigM

58 58


In [43]:
print(BigM[0:3,0:3])  # A 3x3 sub array inside BigM
print(BigM[5:8,3:6])  # A 3x3 sub array inside BigM
print(BigM[5:9:2,3:7:2])  # A 2x2 sub array inside BigM, skipping every other

[[ 0  1  2]
 [10 11 12]
 [20 21 22]]
[[53 54 55]
 [63 64 65]
 [73 74 75]]
[[53 55]
 [73 75]]


You can also **assign** to a slice, by putting the slice **on the other side of =**.
First, we want to make a copy of BigM, so we don't overwrite it. 
We also see assignment to a single element here.

In [44]:
BigM_ref = BigM  # This makes a reference, not a copy. 
                 # Any change to BigM_ref will also happen in BigM
BigM_copy = BigM.copy()
tmp = BigM[3,3]
BigM_ref[3,3] = 99999  # This changed the [3,3] of BigM as well!!!
print(BigM[3,3])       # Check it.
BigM[3,3] = tmp        # restore to old value
BigM_copy[3,3] = 99999 # Only changes the copy.
print(BigM[3,3],BigM_ref[3,3],BigM_copy[3,3])       # Check it.

99999
33 33 99999


You can also assign to a whole slice.

In [45]:
BigM_copy[2,0:5] = 12345 # Set the 2 row, columns 0 through 4 to 12345
print(BigM_copy)

[[    0     1     2     3     4     5     6     7     8     9]
 [   10    11    12    13    14    15    16    17    18    19]
 [12345 12345 12345 12345 12345    25    26    27    28    29]
 [   30    31    32 99999    34    35    36    37    38    39]
 [   40    41    42    43    44    45    46    47    48    49]
 [   50    51    52    53    54    55    56    57    58    59]
 [   60    61    62    63    64    65    66    67    68    69]
 [   70    71    72    73    74    75    76    77    78    79]
 [   80    81    82    83    84    85    86    87    88    89]
 [   90    91    92    93    94    95    96    97    98    99]]


Sometimes you want to be able to find all those cells in an array or matrix that obey a certain condition. You can make a "mask" matrix of True and False values, and then use the np.where() function to find where the mast has "True".

In [46]:
MaskM = (BigM > 50)*(BigM < 60) # This is a 10x10 array, with True where BigM > 50 and False for BigM<=50
(ys,xs) = np.where(MaskM) # Two arrays, one with the x indexes and one with the y indexes, 
                         # where BigM is larger than50
print(BigM[ys[0],xs[0]]) # Check the first one of the values.

51


In [47]:
print(np.diag(BigM) )    # Get the diagonal elements of BigM. 
print(np.diag(BigM,1))   # Get the one offset diagonal elements

[ 0 11 22 33 44 55 66 77 88 99]
[ 1 12 23 34 45 56 67 78 89]


For more on Numpy, read the documentation or read the books.